### ISSUE TITLE
VSC PHP Language Server: Unhandled Exception

### ISSUE THREAD

**Issue by Mordef** [DEVSENSE/phptools-docs#1]
Unhandled Exception: 
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Devsense.PHP.ControlFlow.Analysis.Visitors.TablesAnalysisVisitor.PrepareCallSignature(ITableFunction info, CallSignature callsignature)
   at Devsense.PHP.ControlFlow.Analysis.Visitors.TablesAnalysisVisitor.<>c__DisplayClass52_0.<HandleMethodCall>b__1(ITableFunction info)
   at Devsense.PHP.ControlFlow.Analysis.Visitors.TablesAnalysisVisitor.HandleMemberUseInternal[T](TypeRefMask ofType, Span ofTypeSpan, TypeRef ofTypeRef, Func`2 resolveMember, Func`2 evaluateMember, Action evaluateUnknownMember, Func`2 mergeMembers, Action checkMemberNotFound, Action`3 checkTypeRef)
   at Devsense.PHP.ControlFlow.Analysis.Visitors.TablesAnalysisVisitor.HandleMethodCall(Name name, Span nameSpan, TypeRefMask ofType, Span ofTypeSpan, TypeRef ofTypeRef, CallSignature callsignature)
   at Devsense.PHP.ControlFlow.Analysis.Visitors.TablesAnalysisVisitor.HandleFunctionCall(DirectFcnCall fcn)
   at Devsense.PHP.ControlFlow.Analysis.Visitors.ExpressionAnalysisVisitor.VisitDirectFcnCall(DirectFcnCall x, ConditionBranch branch)
   at Devsense.PHP.ControlFlow.Graph.GraphVisitor.VisitCFGBlockStatements(Block x)
   at Devsense.PHP.ControlFlow.Graph.GraphVisitor.VisitCFGBlockInternal(Block x)
   at Devsense.PHP.ControlFlow.Analysis.Visitors.AnalysisVisitor.VisitCFG(ControlFlowGraph x)
   at Devsense.PHP.ControlFlow.Analysis.Visitors.ExpressionAnalysisVisitor.VisitCFG(ControlFlowGraph x)
   at Devsense.PHP.ControlFlow.Analysis.Visitors.TablesAnalysisVisitor.VisitCFG(ControlFlowGraph x)
   at Devsense.PHP.ControlFlow.Analysis.Visitors.CheckAnalysisVisitor.VisitCFG(ControlFlowGraph x)
   at Devsense.PHP.ControlFlow.Analysis.State.AnalyseCfg(ControlFlowGraph cfg, LambdaFunctionExprHandler handleLambdaExpr, IRoutine routine, CallInfo call, LocalsState callState, ITables tables, ErrorAnalysisSettings errSettings)
   at PHP.VisualStudio.Language.Nodes.Project.ProjectAnalysis.AnalyseRoutine(IRoutine routine, CallInfo call, LocalsState callState)
   at PHP.VisualStudio.Language.Nodes.Project.ProjectAnalysis.EnsureRoutineAnalysed(IRoutine routine)
   at PHP.VisualStudio.Language.Nodes.Project.ProjectAnalysis.AnalyseNodeNoLock(GlobalCodeNode node)
   at PHP.VisualStudio.Language.Nodes.Project.ProjectAnalysis.AnalyseNode(GlobalCodeNode node)
   at Devsense.PHP.LanguageServer.Project.WorkspaceProject.<.ctor>b__11_0(Object o) in C:\agent\_work\10\s\src\Devsense.PHP.LanguageServer\Project\WorkspaceProject.cs:line 80
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
[Info  - 8:00:30 AM] Connection to server got closed. Server will restart.
[Error - 8:00:30 AM] Request textDocument/signatureHelp failed.
Error: Connection got disposed.
    at Object.dispose (C:\Users\mwaac\.vscode\extensions\devsense.phptools-vscode-1.0.2821\node_modules\vscode-languageclient\node_modules\vscode-jsonrpc\lib\main.js:876:25)
    at Object.dispose (C:\Users\mwaac\.vscode\extensions\devsense.phptools-vscode-1.0.2821\node_modules\vscode-languageclient\lib\client.js:71:35)
    at LanguageClient.handleConnectionClosed (C:\Users\mwaac\.vscode\extensions\devsense.phptools-vscode-1.0.2821\node_modules\vscode-languageclient\lib\client.js:2143:42)
    at LanguageClient.handleConnectionClosed (C:\Users\mwaac\.vscode\extensions\devsense.phptools-vscode-1.0.2821\node_modules\vscode-languageclient\lib\main.js:150:15)
    at closeHandler (C:\Users\mwaac\.vscode\extensions\devsense.phptools-vscode-1.0.2821\node_modules\vscode-languageclient\lib\client.js:2130:18)
    at CallbackList.invoke (C:\Users\mwaac\.vscode\extensions\devsense.phptools-vscode-1.0.2821\node_modules\vscode-languageclient\node_modules\vscode-jsonrpc\lib\events.js:62:39)
    at Emitter.fire (C:\Users\mwaac\.vscode\extensions\devsense.phptools-vscode-1.0.2821\node_modules\vscode-languageclient\node_modules\vscode-jsonrpc\lib\events.js:120:36)
    at closeHandler (C:\Users\mwaac\.vscode\extensions\devsense.phptools-vscode-1.0.2821\node_modules\vscode-languageclient\node_modules\vscode-jsonrpc\lib\main.js:226:26)
    at CallbackList.invoke (C:\Users\mwaac\.vscode\extensions\devsense.phptools-vscode-1.0.2821\node_modules\vscode-languageclient\node_modules\vscode-jsonrpc\lib\events.js:62:39)
    at Emitter.fire (C:\Users\mwaac\.vscode\extensions\devsense.phptools-vscode-1.0.2821\node_modules\vscode-languageclient\node_modules\vscode-jsonrpc\lib\events.js:120:36)
    at StreamMessageReader.fireClose (C:\Users\mwaac\.vscode\extensions\devsense.phptools-vscode-1.0.2821\node_modules\vscode-languageclient\node_modules\vscode-jsonrpc\lib\messageReader.js:111:27)
    at Socket.readable.on (C:\Users\mwaac\.vscode\extensions\devsense.phptools-vscode-1.0.2821\node_modules\vscode-languageclient\node_modules\vscode-jsonrpc\lib\messageReader.js:151:46)
    at emitOne (events.js:121:20)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)

PHP Tools server started.
    Path: c:\Users\mwaac\.vscode\extensions\devsense.phptools-vscode-1.0.2821\out\server\Devsense.PHP.LanguageServer.dll
    PID: 12216
    Processing files: .php; .php5

**Comment by jakubmisek** [comment]
thanks for reporting the issue! fixed

ref https://devsense.visualstudio.com/PhalangerTools/_versionControl/changeset/11002
