### ISSUE TITLE
Add quick fix to implement interface methods

### ISSUE THREAD

**Issue by Zerotask** [DEVSENSE/phptools-docs#190]
Assume you have the following:
```php
<?php

interface TestInterface
{
    public function getName(int $id): ?string;
}

class User implements TestInterface
{
}
```

A quick fix for the class (User here) which implements an interface (or multiple) to implement method stubs.
There can be 2 quick fixes (if possible):
1. quick fix to implement all method stubs for a **single interface** (e.g. `class User implements InterfaceA`)
2. quick fix for the class to implement method stubs from **all interfaces** (e. g. `class User implements InterfaceA, InterfaceB, InterfaceC`)

A method stub could look like:
```php
<?php

class User implements TestInterface
{
    public function getName(int $id): ?string
    {
        // TODO implement method.
    }
}
```

Optimally it only create method stubs if there isn't already a method with that name.

**Comment by jakubmisek** [comment]
we have a quick fix for that:
![image](https://user-images.githubusercontent.com/842150/200076058-0910c1fd-dba0-4053-af15-3ebe97c85161.png)

But we can improve the generated code as you described, and also we can have separate quick fixes for separate interfaces )

**Comment by Zerotask** [comment]
That's strange. I don't see it.
![image](https://user-images.githubusercontent.com/20150243/200076452-2caed904-cf4d-4304-8715-4456e264b793.png)

**Comment by jakubmisek** [comment]
weird, you should also have it underlined because it is missing the method implementations.

**Comment by Zerotask** [comment]
I got it underlined only if I install other PHP extensions like PHP Intelephense, but still no quick fix.
Do you have other PHP extensions installed? If not, can you provide me your PHP Tools config?

**Comment by jakubmisek** [comment]
only [php tools](https://marketplace.visualstudio.com/items?itemName=DEVSENSE.phptools-vscode)

Isn't the file in a folder that is excluded? or excluded from problems?

**Comment by Zerotask** [comment]
I excluded `vendor/**` and `var/**` and it's not in .gitignore, also tried several other existing files.
But I just delete some extensions I rarely use and did some restarts and now I finally see it.
Although I got the error "Canceled" if I click on the quick fix.
![image](https://user-images.githubusercontent.com/20150243/200082791-20a12a1a-7fdc-435f-a7c5-ed5b47b10235.png)

![image](https://user-images.githubusercontent.com/20150243/200082842-0bb7c4aa-3abe-49e2-bad4-fafbfbbead57.png)

**Comment by jakubmisek** [comment]
Alright, we're getting somewhere :)

May I ask to check the error details? in `Help`/`Toggle Developer Tools`, tab `Console` - there will be a red error with stack trace.

**Comment by jakubmisek** [comment]
Also, I don't know what the red **Class User does no....** - seems like something from another extension?

**Comment by Zerotask** [comment]
I checked the Console and as soon as I click on "TestInterface" I get a lot of text
<details>
  ERR Cannot read properties of undefined (reading 'find'): TypeError: Cannot read properties of undefined (reading 'find')
    at ServiceDocumentationCodeActionProvider.provideCodeActions (/home/phintermayer/.vscode-server/extensions/thenouillet.symfony-vscode-1.0.2/out/mvc/editing/codeaction/ServiceDocumentationCodeActionProvider.js:20:70)
    at x.provideCodeActions (/home/phintermayer/.vscode-server/bin/8fa188b2b301d36553cbc9ce1b0a146ccb93351f/out/vs/workbench/api/node/extensionHostProcess.js:94:43028)
    at /home/phintermayer/.vscode-server/bin/8fa188b2b301d36553cbc9ce1b0a146ccb93351f/out/vs/workbench/api/node/extensionHostProcess.js:94:73290
    at ne._withAdapter (/home/phintermayer/.vscode-server/bin/8fa188b2b301d36553cbc9ce1b0a146ccb93351f/out/vs/workbench/api/node/extensionHostProcess.js:94:67325)
    at ne.$provideCodeActions (/home/phintermayer/.vscode-server/bin/8fa188b2b301d36553cbc9ce1b0a146ccb93351f/out/vs/workbench/api/node/extensionHostProcess.js:94:73266)
    at l._doInvokeHandler (/home/phintermayer/.vscode-server/bin/8fa188b2b301d36553cbc9ce1b0a146ccb93351f/out/vs/workbench/api/node/extensionHostProcess.js:102:13680)
    at l._invokeHandler (/home/phintermayer/.vscode-server/bin/8fa188b2b301d36553cbc9ce1b0a146ccb93351f/out/vs/workbench/api/node/extensionHostProcess.js:102:13362)
    at l._receiveRequest (/home/phintermayer/.vscode-server/bin/8fa188b2b301d36553cbc9ce1b0a146ccb93351f/out/vs/workbench/api/node/extensionHostProcess.js:102:12081)
    at l._receiveOneMessage (/home/phintermayer/.vscode-server/bin/8fa188b2b301d36553cbc9ce1b0a146ccb93351f/out/vs/workbench/api/node/extensionHostProcess.js:102:10834)
    at /home/phintermayer/.vscode-server/bin/8fa188b2b301d36553cbc9ce1b0a146ccb93351f/out/vs/workbench/api/node/extensionHostProcess.js:102:8941
    at h.invoke (/home/phintermayer/.vscode-server/bin/8fa188b2b301d36553cbc9ce1b0a146ccb93351f/out/vs/workbench/api/node/extensionHostProcess.js:61:145)
    at v.deliver (/home/phintermayer/.vscode-server/bin/8fa188b2b301d36553cbc9ce1b0a146ccb93351f/out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
    at g.fire (/home/phintermayer/.vscode-server/bin/8fa188b2b301d36553cbc9ce1b0a146ccb93351f/out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
    at r.fire (/home/phintermayer/.vscode-server/bin/8fa188b2b301d36553cbc9ce1b0a146ccb93351f/out/vs/workbench/api/node/extensionHostProcess.js:70:16515)
    at /home/phintermayer/.vscode-server/bin/8fa188b2b301d36553cbc9ce1b0a146ccb93351f/out/vs/workbench/api/node/extensionHostProcess.js:118:17104
    at h.invoke (/home/phintermayer/.vscode-server/bin/8fa188b2b301d36553cbc9ce1b0a146ccb93351f/out/vs/workbench/api/node/extensionHostProcess.js:61:145)
    at v.deliver (/home/phintermayer/.vscode-server/bin/8fa188b2b301d36553cbc9ce1b0a146ccb93351f/out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
    at g.fire (/home/phintermayer/.vscode-server/bin/8fa188b2b301d36553cbc9ce1b0a146ccb93351f/out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
    at r.fire (/home/phintermayer/.vscode-server/bin/8fa188b2b301d36553cbc9ce1b0a146ccb93351f/out/vs/workbench/api/node/extensionHostProcess.js:70:16515)
    at o._receiveMessage (/home/phintermayer/.vscode-server/bin/8fa188b2b301d36553cbc9ce1b0a146ccb93351f/out/vs/workbench/api/node/extensionHostProcess.js:70:21327)
    at /home/phintermayer/.vscode-server/bin/8fa188b2b301d36553cbc9ce1b0a146ccb93351f/out/vs/workbench/api/node/extensionHostProcess.js:70:18770
    at h.invoke (/home/phintermayer/.vscode-server/bin/8fa188b2b301d36553cbc9ce1b0a146ccb93351f/out/vs/workbench/api/node/extensionHostProcess.js:61:145)
    at v.deliver (/home/phintermayer/.vscode-server/bin/8fa188b2b301d36553cbc9ce1b0a146ccb93351f/out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
    at g.fire (/home/phintermayer/.vscode-server/bin/8fa188b2b301d36553cbc9ce1b0a146ccb93351f/out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
    at g.acceptChunk (/home/phintermayer/.vscode-server/bin/8fa188b2b301d36553cbc9ce1b0a146ccb93351f/out/vs/workbench/api/node/extensionHostProcess.js:70:13346)
    at /home/phintermayer/.vscode-server/bin/8fa188b2b301d36553cbc9ce1b0a146ccb93351f/out/vs/workbench/api/node/extensionHostProcess.js:70:12476
    at h.invoke (/home/phintermayer/.vscode-server/bin/8fa188b2b301d36553cbc9ce1b0a146ccb93351f/out/vs/workbench/api/node/extensionHostProcess.js:61:145)
    at v.deliver (/home/phintermayer/.vscode-server/bin/8fa188b2b301d36553cbc9ce1b0a146ccb93351f/out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
    at g.fire (/home/phintermayer/.vscode-server/bin/8fa188b2b301d36553cbc9ce1b0a146ccb93351f/out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
    at g._processReadQueue (/home/phintermayer/.vscode-server/bin/8fa188b2b301d36553cbc9ce1b0a146ccb93351f/out/vs/workbench/api/node/extensionHostProcess.js:70:32036)
    at g.acceptFrame (/home/phintermayer/.vscode-server/bin/8fa188b2b301d36553cbc9ce1b0a146ccb93351f/out/vs/workbench/api/node/extensionHostProcess.js:70:31692)
    at h._acceptChunk (/home/phintermayer/.vscode-server/bin/8fa188b2b301d36553cbc9ce1b0a146ccb93351f/out/vs/workbench/api/node/extensionHostProcess.js:70:29656)
    at /home/phintermayer/.vscode-server/bin/8fa188b2b301d36553cbc9ce1b0a146ccb93351f/out/vs/workbench/api/node/extensionHostProcess.js:70:26841
    at Socket.i (/home/phintermayer/.vscode-server/bin/8fa188b2b301d36553cbc9ce1b0a146ccb93351f/out/vs/workbench/api/node/extensionHostProcess.js:70:24594)
    at Socket.emit (node:events:526:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
notificationsAlerts.ts:42 Canceled
</details>

**Comment by Zerotask** [comment]
Besides the error, there is also a suggestions for the generated code:
```php
/**
	 *
	 * @param int $id
	 *
	 * @return null|string
	 */
	function getName(int $id): null|string {
	}
```

1. add visibility (in the interface is `public` given)
2. return type `null|string` -> `?string` (as in the interface)

**Comment by Zerotask** [comment]
> Also, I don't know what the red **Class User does no....** - seems like something from another extension?

This is from the extension Error Lens (https://marketplace.visualstudio.com/items?itemName=usernamehw.errorlens). It just inlines the error message.
The complete message is:
![image](https://user-images.githubusercontent.com/20150243/200083971-d5e8aa8a-f15d-4c9c-937e-1a74561fd312.png)

**Comment by jakubmisek** [comment]
> This is from the extension Error Lens
nice! I didn't know that

**Comment by jakubmisek** [comment]
> I checked the Console and as soon as I click on "TestInterface" I get a lot of text

This looks like the extension `thenouillet.symfony-vscode-1.0.2` throws an error - so this /**might**/ break the quick fix.

**Comment by jakubmisek** [comment]
> Besides the error, there is also a suggestions for the generated code:

good idea, I've created a separate issue for that at https://github.com/DEVSENSE/phptools-docs/issues/197

**Comment by Zerotask** [comment]
> ```
> <?php
> 
> interface TestInterface
> {
>     public function getName(int $id): ?string;
> }
> 
> class User implements TestInterface
> {
> }
> ```

I uninstalled it and restarted vscode. The problem seems to occur less and I don't get the error messages when I click on the interface name.
Although I still get often the "Canceled" message without any errors in the Console.
![image](https://user-images.githubusercontent.com/20150243/200114047-684f9e1d-ee27-4077-9afa-c7e88798c306.png)

Directly after opening the file and using the quick fix, it works, but if I delete the method and re-try it or if I create a new class (e. g. `User2`) and implement the interface, the quick fix doesn't work.

**Comment by jakubmisek** [comment]
thanks! I think we've found the possible culprit - working on it.

(note for me: LS thinks the file is not opened in editor `!IsInEditor`)

**Comment by jakubmisek** [comment]
This should be fixed already. Please reopen if it happens again.
