### ISSUE TITLE
Can`t install php tools in code-insiders.

### ISSUE THREAD

**Issue by Timbuktu1982** [DEVSENSE/phptools-docs#212]
Hi there, 
when i want to install the package from vs marketplace, the install failed with following message:

```
2022-12-02 08:20:33.773 [error] UnknownError,UnknownError: Error: UnknownError,UnknownError
    at vscode-file://vscode-app/snap/code-insiders/1168/usr/share/code-insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:88542
    at Array.reduce (<anonymous>)
    at u (vscode-file://vscode-app/snap/code-insiders/1168/usr/share/code-insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:88528)
    at Z.D (vscode-file://vscode-app/snap/code-insiders/1168/usr/share/code-insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:79848)
    at async Z.z (vscode-file://vscode-app/snap/code-insiders/1168/usr/share/code-insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:77382)
    at async Z.installFromGallery (vscode-file://vscode-app/snap/code-insiders/1168/usr/share/code-insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:73871)
```

What went wrong?

**Comment by jakubmisek** [comment]
Hi @Timbuktu1982 - this looks more like an issue in code-insiders itself.

Does it happen with other extensions?

I'd report it to https://github.com/microsoft/vscode/issues instead, since there is not much we can do.

**Comment by jakubmisek** [comment]
for the reference, we're tracking the issue on https://community.devsense.com/d/703-can-t-install-in-code-server as well
