### ISSUE TITLE
VSCode extension 1.32.12908 causes high CPU consumption

### ISSUE THREAD

**Issue by zengbo** [DEVSENSE/phptools-docs#314]
When I upgrade the VSCode extension to 1.32.12908, it causes high CPU load.

**Comment by jakubmisek** [comment]
Thank you for the feedback.

We haven't changed much related to CPU load. Is it constant or just during opening the workspace?

**Comment by zengbo** [comment]
During opening the workspace.
But the previous version does not

**Comment by jakubmisek** [comment]
I'll do more profiling of what's going on there

**Comment by jakubmisek** [comment]
@bymem Thank you for the information. We'll try the extension.

May I ask you to check the process monitor (Process Monitor on macOS, Task Manager on Windows)? What process is consuming most CPU?

**Comment by bymem** [comment]
I have include one where vs code is locked, and one where it's not.
<img width="2559" alt="Screenshot 2023-04-12 at 12 14 58" src="https://user-images.githubusercontent.com/1265623/231430939-11f90768-111a-48ce-8b36-1a0d09c67185.png">
<img width="2166" alt="Screenshot 2023-04-12 at 12 13 27" src="https://user-images.githubusercontent.com/1265623/231430951-f33e700b-b1e3-4e8e-8745-71e8f47f910c.png">

**Comment by jakubmisek** [comment]
Thank you. It's definitely doing something. Are there all the processes? Our process would be something like `.../devsense.php.ls`

**Comment by jakubmisek** [comment]
@bymem sorry - on macOS the app is called "Activity Monitor". You'll find more details there.

**Comment by jakubmisek** [comment]
Thank you. It looks like `"Code Helper (Plugin)"` and `"Code Helper (Renderer)"` are using all the CPU. There are already reported issues happening on macOS, i.e. on 

- https://apple.stackexchange.com/questions/351761/vs-code-code-helper-process-using-more-than-100-cpu-on-macos
- https://github.com/microsoft/vscode/issues/101555

As far as I know, we shouldn't do any updating/refreshing of VSCode, but just in case - Is there any related error/warning in VSCode developer console? (Help -> Toggle Developer Tools -> Console)

**Comment by bymem** [comment]
Yup there seems to be couple.

```
 WARN Ignoring the error while validating workspace folder ssh://srv02/var/www/vhosts - ENOPRO: No file system provider found for resource 'ssh://srv02/var/www/vhosts'
log.ts:431  WARN Via 'product.json#extensionEnabledApiProposals' extension 'ms-vscode.vscode-selfhost-test-provider' wants API proposal 'testContinuousRun' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
log.ts:431  WARN Via 'product.json#extensionEnabledApiProposals' extension 'ms-vscode.remote-repositories' wants API proposal 'contribEditorGutterMenu' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
log.ts:431  WARN Via 'product.json#extensionEnabledApiProposals' extension 'github.vscode-pull-request-github' wants API proposal 'contribEditorGutterMenu' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
log.ts:431  WARN Via 'product.json#extensionEnabledApiProposals' extension 'ms-toolsai.jupyter' wants API proposal 'notebookControllerKind' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
log.ts:441   ERR Extension 'github.copilot' appears in product.json but enables LESS API proposals than the extension wants.
package.json (LOSES): inlineCompletionsAdditions, interactive, terminalDataWriteEvent
product.json (WINS): inlineCompletionsAdditions
console.ts:137 [Extension Host] [vscode-sshfs] Debug mode set to false
T @ console.ts:137
12log.ts:441   ERR [Hridoy.jquery-snippets]: Unknown language in `contributes.jquery-snippets.language`. Provided value: 'javascript'
console.ts:137 [Extension Host] TypeError: Cannot read properties of undefined (reading 'uri')
	at /Users/mikkel/.vscode/extensions/atishay-jain.all-autocomplete-0.0.26/dist/extension.js:2:21850
	at Generator.next (<anonymous>)
	at o (/Users/mikkel/.vscode/extensions/atishay-jain.all-autocomplete-0.0.26/dist/extension.js:2:17467)
console.ts:137 [Extension Host] rejected promise not handled within 1 second: Error: ENOENT: no such file or directory, scandir '/var/www/vhosts'
T @ console.ts:137
console.ts:137 [Extension Host] stack trace: Error: ENOENT: no such file or directory, scandir '/var/www/vhosts'
T @ console.ts:137
log.ts:441   ERR ENOENT: no such file or directory, scandir '/var/www/vhosts': Error: ENOENT: no such file or directory, scandir '/var/www/vhosts'
notificationsAlerts.ts:42 Error handling readFile for: ssh://srv02/var/www/vhosts/pyproject.toml ssh://srv02/var/www/vhosts/pyproject.toml
c @ notificationsAlerts.ts:42
log.ts:421  INFO [perf] Render performance baseline is 41ms
localProcessExtensionHost.ts:293 Extension Host
localProcessExtensionHost.ts:294 Debugger attached.
log.ts:421  INFO UNRESPONSIVE extension host: starting to profile NOW
log.ts:421  INFO UNRESPONSIVE extension host: received responsive event and cancelling profiling session
console.ts:137 [Extension Host] ApplicationInsights:unable to read app version:  Array(1)
log.ts:441   ERR [Extension Host] /Users/mikkel/.vscode/extensions/devsense.phptools-vscode-1.33.12934-darwin-x64/out/server/devsense.php.ls: is already signed
console.ts:137 [Extension Host] /Users/mikkel/.vscode/extensions/devsense.phptools-vscode-1.33.12934-darwin-x64/out/server/devsense.php.ls: is already signed
T @ console.ts:137
console.ts:137 [Extension Host] ApplicationInsights:unable to read app version:  Array(1)
console.ts:137 [Extension Host] ApplicationInsights:CorrelationIdManager Array(1)
localProcessExtensionHost.ts:293 Extension Host
localProcessExtensionHost.ts:294 /Users/mikkel/.vscode/extensions/devsense.phptools-vscode-1.33.12934-darwin-x64/out/server/devsense.php.ls: is already signed
console.ts:137 [Extension Host] ApplicationInsights:CorrelationIdManager Array(1)
notificationsAlerts.ts:42 Error handling readFile for: ssh://srv02/var/www/vhosts/composer.json ssh://srv02/var/www/vhosts/composer.json
c @ notificationsAlerts.ts:42
log.ts:441   ERR [Extension Host] /bin/sh: php: command not found
console.ts:137 [Extension Host] /bin/sh: php: command not found
T @ console.ts:137
localProcessExtensionHost.ts:293 Extension Host
localProcessExtensionHost.ts:294 /bin/sh: php: command not found
console.ts:137 [Extension Host] ApplicationInsights:CorrelationIdManager Array(1)
console.ts:137 [Extension Host] ApplicationInsights:CorrelationIdManager Array(1)
log.ts:431  WARN No search provider registered for scheme: ssh, waiting
console.ts:137 [Extension Host] ApplicationInsights:Sender Array(1)
console.ts:137 [Extension Host] ApplicationInsights:Sender Array(1)
console.ts:137 [Extension Host] ApplicationInsights:Sender Array(1)
console.ts:137 [Extension Host] ApplicationInsights:Sender Array(1)
localProcessExtensionHost.ts:293 Extension Host
localProcessExtensionHost.ts:294 Debugger attached.
log.ts:421  INFO UNRESPONSIVE extension host: starting to profile NOW
log.ts:441   ERR Error: Aborted onWillSaveTextDocument-event after 1750ms
    at mainThreadSaveParticipant.ts:37:18
log.ts:421  INFO UNRESPONSIVE extension host: received responsive event and cancelling profiling session
localProcessExtensionHost.ts:293 Extension Host
localProcessExtensionHost.ts:294 Debugger attached.
log.ts:421  INFO UNRESPONSIVE extension host: starting to profile NOW
log.ts:421  INFO UNRESPONSIVE extension host: received responsive event and cancelling profiling session
log.ts:441   ERR Error: Aborted onWillSaveTextDocument-event after 1750ms
    at mainThreadSaveParticipant.ts:37:18
localProcessExtensionHost.ts:293 Extension Host
localProcessExtensionHost.ts:294 Debugger attached.
log.ts:421  INFO UNRESPONSIVE extension host: starting to profile NOW
log.ts:421  INFO UNRESPONSIVE extension host: received responsive event and cancelling profiling session
localProcessExtensionHost.ts:293 Extension Host
localProcessExtensionHost.ts:294 Debugger attached.
log.ts:421  INFO UNRESPONSIVE extension host: starting to profile NOW
log.ts:421  INFO UNRESPONSIVE extension host: received responsive event and cancelling profiling session
```

**Comment by jakubmisek** [comment]
Thanks, there is something happening. Sadly no warnings from our `devsense.php.lsp` (except for the code signing thing), so I don't have many clues about what we're doing wrong or doing excessively.

It looks like some extensions are broken, or some VSCode configurations may be broken or misconfigured.

- Aren't there any updates available? 
- Do you have some `"editor.codeActionsOnSave"` setting that might get involved?

**Comment by bymem** [comment]
Yeah i tried deactivating all my plugins besides the SSH extension and the problem persists, so i'm guessing that one could be the culprit.

**Comment by jakubmisek** [comment]
Thank you @bymem - still looking into it, but we couldn't reproduce the issue on our machines.

> log.ts:421  INFO UNRESPONSIVE extension host: starting to profile NOW

VSCode should have done "profiling" giving you some profiling logs to analyze. Do you have the file somewhere? It would be a .txt file that would help us to find out what's going on

**Comment by bymem** [comment]
> Thank you @bymem - still looking into it, but we couldn't reproduce the issue on our machines.
> 
> > log.ts:421  INFO UNRESPONSIVE extension host: starting to profile NOW
> 
> VSCode should have done "profiling" giving you some profiling logs to analyze. Do you have the file somewhere? It would be a .txt file that would help us to find out what's going on

Hi i have narrowed down my problem to the SSH FS extension, i have to resort to revert back to a older version of VS Code and the extension. Have then activated the PHPtools again and they work perfectly for me at least, so sorry for the confusion.

**Comment by jakubmisek** [comment]
@bymem I'm glad you have resolved the issue, and thank you for keeping us informed.

Please feel free to report anything else unusual in the future.
