### ISSUE TITLE
Unhandled exception. System.ArgumentOutOfRangeException: Arg_ArgumentOutOfRangeException Arg_ParamName_Name, length

### ISSUE THREAD

**Issue by planetgreensolutions** [DEVSENSE/phptools-docs#332]
The extension has been crashing multiple times and here's the log:

```
PHP Tools server started.
    PID: 9624
    Processing files: *.php; *.phtml

Internal Error, please report it to https://github.com/devsense/phptools-docs/issues 
Arg_ArgumentOutOfRangeException Arg_ParamName_Name, length
   at Devsense.PHP.Text.Span..ctor(Int32 start, Int32 length)
   at Devsense.PHP.Text.Span.FromBounds(Int32 start, Int32 end)
   at Devsense.PHP.LSP.Text.TrackingExtensions.TryMapToSource(TextProjection projection, Span span, Span& mapped)
   at Devsense.PHP.LanguageServer.Text.TextMapping.MapToSource(Span span)
   at Devsense.PHP.LanguageServer.Text.TextMapping.MapToSourceRange(Span span)
   at Devsense.LanguageServer.Utils.ErrorUtils.ToDiagnostic(CommonError error, TextMapping mapping)
   at Devsense.LanguageServer.Utils.ErrorUtils.ToDiagnostic(CommonError error, PhpSourceUnit unit)
   at Devsense.PHP.LanguageServer.PhpLanguageServer.GetDiagnostics(FileErrors p)+MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at Devsense.PHP.LanguageServer.JsonRpc.JsonHelper.WriteJsonValue(Utf8JsonWriter output, IEnumerable enumerable)
   at Devsense.PHP.LanguageServer.JsonRpc.JsonHelper.WriteJsonValue[T](Utf8JsonWriter output, T data)
   at Devsense.LanguageServer.Protocol.PublishDiagnosticsParams.Devsense.PHP.LanguageServer.JsonRpc.IJsonSerializable.Serialize(Utf8JsonWriter output)
   at Devsense.PHP.LanguageServer.JsonRpc.JsonHelper.WriteJsonValue[T](Utf8JsonWriter output, T data)
   at Devsense.PHP.LanguageServer.JsonRpc.RpcNotification`1.Devsense.PHP.LanguageServer.JsonRpc.IJsonSerializable.Serialize(Utf8JsonWriter output)
   at Devsense.PHP.LanguageServer.JsonRpc.JsonHelper.WriteJsonValue[T](Utf8JsonWriter output, T data)
   at Devsense.PHP.LanguageServer.JsonRpc.CommonMessageWriter.SerializeAndSend[T](T data, Boolean log)
   at Devsense.PHP.LanguageServer.JsonRpc.CommonMessageWriter.WriteNotification[T](String method, T parameters)
   at Devsense.PHP.LanguageServer.JsonRpc.CommonMessageWriter.ShowDiagnostics(String fileUri, IEnumerable`1 diagnostics)
   at Devsense.PHP.LanguageServer.PhpLanguageServer.SendErrors(IList`1 ferrors)
   at Devsense.PHP.LanguageServer.PhpLanguageServer.PollAsync()
   at Devsense.PHP.LanguageServer.PhpLanguageServer.Devsense.PHP.LSP.Threading.IWorker.NextAsync()
   at Devsense.PHP.LanguageServer.Threading.WorkerFactoryExtensions.RunAsync(IWorker worker, CancellationToken cancellation)
   at Devsense.PHP.LanguageServer.Program.Main(String[] args)
Unhandled exception. System.ArgumentOutOfRangeException: Arg_ArgumentOutOfRangeException Arg_ParamName_Name, length
   at Devsense.PHP.Text.Span..ctor(Int32 start, Int32 length)
   at Devsense.PHP.Text.Span.FromBounds(Int32 start, Int32 end)
   at Devsense.PHP.LSP.Text.TrackingExtensions.TryMapToSource(TextProjection projection, Span span, Span& mapped)
   at Devsense.PHP.LanguageServer.Text.TextMapping.MapToSource(Span span)
   at Devsense.PHP.LanguageServer.Text.TextMapping.MapToSourceRange(Span span)
   at Devsense.LanguageServer.Utils.ErrorUtils.ToDiagnostic(CommonError error, TextMapping mapping)
   at Devsense.LanguageServer.Utils.ErrorUtils.ToDiagnostic(CommonError error, PhpSourceUnit unit)
   at Devsense.PHP.LanguageServer.PhpLanguageServer.GetDiagnostics(FileErrors p)+MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at Devsense.PHP.LanguageServer.JsonRpc.JsonHelper.WriteJsonValue(Utf8JsonWriter output, IEnumerable enumerable)
   at Devsense.PHP.LanguageServer.JsonRpc.JsonHelper.WriteJsonValue[T](Utf8JsonWriter output, T data)
   at Devsense.LanguageServer.Protocol.PublishDiagnosticsParams.Devsense.PHP.LanguageServer.JsonRpc.IJsonSerializable.Serialize(Utf8JsonWriter output)
   at Devsense.PHP.LanguageServer.JsonRpc.JsonHelper.WriteJsonValue[T](Utf8JsonWriter output, T data)
   at Devsense.PHP.LanguageServer.JsonRpc.RpcNotification`1.Devsense.PHP.LanguageServer.JsonRpc.IJsonSerializable.Serialize(Utf8JsonWriter output)
   at Devsense.PHP.LanguageServer.JsonRpc.JsonHelper.WriteJsonValue[T](Utf8JsonWriter output, T data)
   at Devsense.PHP.LanguageServer.JsonRpc.CommonMessageWriter.SerializeAndSend[T](T data, Boolean log)
   at Devsense.PHP.LanguageServer.JsonRpc.CommonMessageWriter.WriteNotification[T](String method, T parameters)
   at Devsense.PHP.LanguageServer.JsonRpc.CommonMessageWriter.ShowDiagnostics(String fileUri, IEnumerable`1 diagnostics)
   at Devsense.PHP.LanguageServer.PhpLanguageServer.SendErrors(IList`1 ferrors)
   at Devsense.PHP.LanguageServer.PhpLanguageServer.PollAsync()
   at Devsense.PHP.LanguageServer.PhpLanguageServer.Devsense.PHP.LSP.Threading.IWorker.NextAsync()
   at Devsense.PHP.LanguageServer.Threading.WorkerFactoryExtensions.RunAsync(IWorker worker, CancellationToken cancellation)
   at Devsense.PHP.LanguageServer.Program.Main(String[] args)
   at Devsense.PHP.LanguageServer.Program.<Main>(String[] args)
[Info  - 10:39:32 AM] Connection to server got closed. Server will restart.
```

I tried uninstalling and reinstalling the extension and didn't really help. 

Please fix this bug.

**Comment by jakubmisek** [comment]
Thank you for the details!

We're fixing the issue, and preparing a pre-release version today.
