### ISSUE TITLE
Cmd+click jump definition crash

### ISSUE THREAD

**Issue by tiansin** [DEVSENSE/phptools-docs#40]
@jakubmisek 
![1](https://user-images.githubusercontent.com/4232281/63336393-aa749a80-c371-11e9-9168-8bda4fc09b11.png)

`Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.

   at Devsense.PHP.Refactoring.Visitors.FindNodeVisitor.VisitTraitsUse(TraitsUse x)

   at Devsense.PHP.Syntax.TreeVisitor.VisitList[T](IList`1 items)

   at Devsense.PHP.Refactoring.Visitors.ContextVisitor.VisitTypeDecl(TypeDecl x)

   at Devsense.PHP.Refactoring.Visitors.FindNodeVisitor.VisitTypeDecl(TypeDecl x)

   at Devsense.PHP.Syntax.TreeVisitor.VisitList[T](IList`1 items)

   at Devsense.PHP.Refactoring.Visitors.ContextVisitor.VisitNamespaceDecl(NamespaceDecl x)

   at Devsense.PHP.Syntax.TreeVisitor.VisitList[T](IList`1 items)

   at Devsense.PHP.Refactoring.Visitors.FindNodeVisitor.FindNodeAt(IFileInfo file, Int32 position, ITypeProvider types)

   at Devsense.PHP.Refactoring.RefactoringFactory.FindReferencesAt(IEnumerable`1 files, ITypeProvider types, IFileInfo fileAt, Int32 positionAt, INodeInfo& node)

   at Devsense.LanguageServer.Utils.NodeUtils.ResolveReferences(TextDocumentPositionParams position, ProjectContainer project, INodeInfo& sourceNode, Boolean thisFileOnly)

   at Devsense.PHP.LanguageServer.PhpLanguageServer.ProcessHighlight(Object requestId, TextDocumentPositionParams position)

   at Devsense.PHP.LanguageServer.PhpLanguageServer.Run()

   at Devsense.PHP.LanguageServer.Program.Main(String[] args)

[Info  - 5:37:24 PM] Connection to server got closed. Server will restart.

[Error - 5:37:24 PM] Request textDocument/documentHighlight failed.

Error: Connection got disposed.

    at Object.dispose (/Users/lover/.vscode/extensions/devsense.phptools-vscode-1.0.3774/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/main.js:876:25)

    at Object.dispose (/Users/lover/.vscode/extensions/devsense.phptools-vscode-1.0.3774/node_modules/vscode-languageclient/lib/client.js:71:35)

    at LanguageClient.handleConnectionClosed (/Users/lover/.vscode/extensions/devsense.phptools-vscode-1.0.3774/node_modules/vscode-languageclient/lib/client.js:2143:42)

    at LanguageClient.handleConnectionClosed (/Users/lover/.vscode/extensions/devsense.phptools-vscode-1.0.3774/node_modules/vscode-languageclient/lib/main.js:150:15)

    at closeHandler (/Users/lover/.vscode/extensions/devsense.phptools-vscode-1.0.3774/node_modules/vscode-languageclient/lib/client.js:2130:18)

    at CallbackList.invoke (/Users/lover/.vscode/extensions/devsense.phptools-vscode-1.0.3774/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/events.js:62:39)

    at Emitter.fire (/Users/lover/.vscode/extensions/devsense.phptools-vscode-1.0.3774/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/events.js:120:36)

    at closeHandler (/Users/lover/.vscode/extensions/devsense.phptools-vscode-1.0.3774/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/main.js:226:26)

    at CallbackList.invoke (/Users/lover/.vscode/extensions/devsense.phptools-vscode-1.0.3774/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/events.js:62:39)

    at Emitter.fire (/Users/lover/.vscode/extensions/devsense.phptools-vscode-1.0.3774/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/events.js:120:36)

    at StreamMessageWriter.fireClose (/Users/lover/.vscode/extensions/devsense.phptools-vscode-1.0.3774/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/messageWriter.js:39:27)

    at Socket.constructor.writable.on (/Users/lover/.vscode/extensions/devsense.phptools-vscode-1.0.3774/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/messageWriter.js:58:46)

    at Socket.emit (events.js:182:13)

    at Socket.EventEmitter.emit (domain.js:442:20)

    at Pipe.Socket._destroy._handle.close (net.js:606:12)

PHP Tools server started.

    Path: /Users/lover/.vscode/extensions/devsense.phptools-vscode-1.0.3774/out/server/Devsense.PHP.LanguageServer.dll

    PID: 5178

    Processing files: .php; .php5

`

**Comment by jakubmisek** [comment]
thank you @tiansin , will be fixed!

**Comment by jakubmisek** [comment]
fixed and ready for the next update. thank you!
