### ISSUE TITLE
(Language server?) process consuming 100% CPU while I'm not even touching VSCode

### ISSUE THREAD

**Issue by php4fan** [DEVSENSE/phptools-docs#461]
I left my computer with VSCode open, and when I came back I noticed the noise of the cooling fan spinning at high speed, so I looked at `top` and I found a **process called `devsense.php.ls` consuming 100% CPU** steadily. I have no idea how long it's been consuming 100% CPU for. Since it's only using up one of a few cores, it doesn't have a noticeable impact on the system's responsiveness, so I only noticed it when it caused the fan to spin faster.

I don't know if this is related to https://github.com/DEVSENSE/phptools-docs/issues/459: I didn't restart since the last occurrence of #459.

Now **I have closed VSCode**, and yet the **`devsense.php.ls` process is still running** and still consuming 100% CPU, which is a whole other level of outrageous.

**Comment by php4fan** [comment]
Possibly related: I just restarted VSCode, and after that, it looks like the PHP Tools server crashed  and restarted:

```
PHP Tools server started.
    PID: 140975
    Processing files: *.php; *.phtml

[Info  - 4:42:57 PM] Parsing phar file '/home/teo/Documents/*****/htdocs/composer.phar' ...
[Info  - 4:42:57 PM] Loaded 4 package(s) from cache in 00:00:00.1724666.
[Info  - 4:42:59 PM] Parsing phar file '/home/teo/Documents/*****/composer.phar' ...
[Info  - 4:43:00 PM] Processing packages in /home/teo/Documents/*****/vendor/composer/installed.json ...
[Info  - 4:43:00 PM] Processing done in 00:00:00.0139053.
[Info  - 4:43:00 PM] Loaded 51 package(s) from cache in 00:00:02.6122738.
[Info  - 4:43:00 PM] Processing packages in /home/teo/Documents/*****/vendor/composer/installed.json ...
[Info  - 4:43:02 PM] Processing done in 00:00:02.0649182.
[Info  - 4:43:27 PM] Connection to server got closed. Server will restart.
[Error - 4:43:27 PM] Request codeLens/resolve failed.
Error: Connection got disposed.
	at Object.dispose (/home/teo/.vscode/extensions/devsense.phptools-vscode-1.42.14626-linux-x64/out/src/extension.js:101:4066)
	at Object.dispose (/home/teo/.vscode/extensions/devsense.phptools-vscode-1.42.14626-linux-x64/out/src/extension.js:106:9593)
	at DE.handleConnectionClosed (/home/teo/.vscode/extensions/devsense.phptools-vscode-1.42.14626-linux-x64/out/src/extension.js:108:9077)
	at DE.handleConnectionClosed (/home/teo/.vscode/extensions/devsense.phptools-vscode-1.42.14626-linux-x64/out/src/extension.js:111:12153)
	at r (/home/teo/.vscode/extensions/devsense.phptools-vscode-1.42.14626-linux-x64/out/src/extension.js:108:8758)
	at RO.invoke (/home/teo/.vscode/extensions/devsense.phptools-vscode-1.42.14626-linux-x64/out/src/extension.js:74:9670)
	at Cu.fire (/home/teo/.vscode/extensions/devsense.phptools-vscode-1.42.14626-linux-x64/out/src/extension.js:74:10436)
	at ge (/home/teo/.vscode/extensions/devsense.phptools-vscode-1.42.14626-linux-x64/out/src/extension.js:75:10894)
	at RO.invoke (/home/teo/.vscode/extensions/devsense.phptools-vscode-1.42.14626-linux-x64/out/src/extension.js:74:9670)
	at Cu.fire (/home/teo/.vscode/extensions/devsense.phptools-vscode-1.42.14626-linux-x64/out/src/extension.js:74:10436)
	at Qh.fireClose (/home/teo/.vscode/extensions/devsense.phptools-vscode-1.42.14626-linux-x64/out/src/extension.js:74:12716)
	at Socket.<anonymous> (/home/teo/.vscode/extensions/devsense.phptools-vscode-1.42.14626-linux-x64/out/src/extension.js:74:14268)
	at Socket.emit (node:events:525:35)
	at Pipe.<anonymous> (node:net:322:12)
[Error - 4:43:27 PM] Request codeLens/resolve failed.
Error: Connection got disposed.
	at Object.dispose (/home/teo/.vscode/extensions/devsense.phptools-vscode-1.42.14626-linux-x64/out/src/extension.js:101:4066)
	at Object.dispose (/home/teo/.vscode/extensions/devsense.phptools-vscode-1.42.14626-linux-x64/out/src/extension.js:106:9593)
	at DE.handleConnectionClosed (/home/teo/.vscode/extensions/devsense.phptools-vscode-1.42.14626-linux-x64/out/src/extension.js:108:9077)
	at DE.handleConnectionClosed (/home/teo/.vscode/extensions/devsense.phptools-vscode-1.42.14626-linux-x64/out/src/extension.js:111:12153)
	at r (/home/teo/.vscode/extensions/devsense.phptools-vscode-1.42.14626-linux-x64/out/src/extension.js:108:8758)
	at RO.invoke (/home/teo/.vscode/extensions/devsense.phptools-vscode-1.42.14626-linux-x64/out/src/extension.js:74:9670)
	at Cu.fire (/home/teo/.vscode/extensions/devsense.phptools-vscode-1.42.14626-linux-x64/out/src/extension.js:74:10436)
	at ge (/home/teo/.vscode/extensions/devsense.phptools-vscode-1.42.14626-linux-x64/out/src/extension.js:75:10894)
	at RO.invoke (/home/teo/.vscode/extensions/devsense.phptools-vscode-1.42.14626-linux-x64/out/src/extension.js:74:9670)
	at Cu.fire (/home/teo/.vscode/extensions/devsense.phptools-vscode-1.42.14626-linux-x64/out/src/extension.js:74:10436)
	at Qh.fireClose (/home/teo/.vscode/extensions/devsense.phptools-vscode-1.42.14626-linux-x64/out/src/extension.js:74:12716)
	at Socket.<anonymous> (/home/teo/.vscode/extensions/devsense.phptools-vscode-1.42.14626-linux-x64/out/src/extension.js:74:14268)
	at Socket.emit (node:events:525:35)
	at Pipe.<anonymous> (node:net:322:12)

PHP Tools server started.
    PID: 141310
    Processing files: *.php; *.phtml

[Info  - 4:43:30 PM] Loaded 4 package(s) from cache in 00:00:00.1182497.
[Info  - 4:43:30 PM] Parsing phar file '/home/teo/Documents/*****/htdocs/composer.phar' ...
[Info  - 4:43:32 PM] Loaded 51 package(s) from cache in 00:00:01.9595574.
[Info  - 4:43:32 PM] Parsing phar file '/home/teo/Documents/*****/ThirdParty/composer.phar' ...
[Info  - 4:43:33 PM] Processing packages in /home/teo/Documents/*****/ThirdParty/vendor/composer/installed.json ...
[Info  - 4:43:33 PM] Processing packages in /home/teo/Documents/*****/vendor/composer/installed.json ...
[Info  - 4:43:33 PM] Processing done in 00:00:00.0027736.
[Info  - 4:43:35 PM] Processing done in 00:00:01.8194492.
```

**Comment by jakubmisek** [comment]
thank you @php4fan - it's weird, it does not crash, just VSCode "closes the connection" ... 

- Do you notice a memory spike before the crash?
- If you disable code lens (`"php.codeLens.enabled"` setting), does it solve the problem?

**Comment by php4fan** [comment]
> Do you notice a memory spike before the crash?

A memory spike is not something that I would normally notice if it happens. However, there's this issue in VSCode itself:
https://github.com/microsoft/vscode/issues/199960
where it often randomly crashes out of the blue (so far I haven't noticed any evident correlation between those  crashes and the issues with the PHP extension), and they found out it's **_"due to OOM in the workbench"_**.

**Comment by jakubmisek** [comment]
We have fixed a few related issues, please comment if it happens again.
