### ISSUE TITLE
error in vscode, when formating the code

### ISSUE THREAD

**Issue by zuhairhasan** [DEVSENSE/phptools-docs#48]
```
PHP Tools server started.
    Path: c:\Users\hasan\.vscode\extensions\devsense.phptools-vscode-1.0.3951\out\server\Devsense.PHP.LanguageServer.dll
    PID: 3528
    Processing files: .php; .php5
```

```
Internal Error, please report it to https://github.com/devsense/phptools-docs/issues 
Unhandled Exception: System.OverflowException: Value was either too large or too small for an Int32.
   at System.Convert.ToInt32(Double value)
   at Newtonsoft.Json.JsonReader.ReadAsInt32()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject[T]()
   at Devsense.PHP.LanguageServer.PhpLanguageServer.Run() in C:\agent\_work\10\s\src\Devsense.PHP.LanguageServer\PhpLanguageServer.cs:line 367
   at Devsense.PHP.LanguageServer.Program.Main(String[] args) in C:\agent\_work\10\s\src\Devsense.PHP.LanguageServer\Program.cs:line 26
```
```
[Error - 9:06:16 PM] Connection to server got closed. Server will not be restarted.
[Error - 9:06:16 PM] Request textDocument/codeAction failed.
Error: Connection got disposed.

[Error - 9:06:16 PM] Request textDocument/foldingRange failed.
Error: Connection got disposed.

[Error - 9:06:16 PM] Request textDocument/codeAction failed.
Error: Connection got disposed.
```

**Comment by jakubmisek** [comment]
Thank you for reporting the issue. Will be fixed in the next update.

Does it happen in large documents or anytime ?

**Comment by zuhairhasan** [comment]
its small file. 89 lines.

**Comment by jakubmisek** [comment]
Thank you. If it would be alright, may I ask to send us the file? here or our email info@devsense.com . It would help us to check we have fixed it correctly.

**Comment by jakubmisek** [comment]
We have released an update which fixes the issue. Please feel free to let us know if it happens again,
