### ISSUE TITLE
Crash in `v1.47.15628 (pre-release)`

### ISSUE THREAD

**Issue by ging-dev** [DEVSENSE/phptools-docs#578]
```plain
Unhandled exception. System.InvalidOperationException: JsonSerializerIsReflectionDisabled
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_JsonSerializerIsReflectionDisabled()
   at System.Text.Json.JsonSerializerOptions.ConfigureForJsonSerializer()
   at System.Text.Json.JsonSerializerOptions.MakeReadOnly(Boolean)
   at System.Text.Json.JsonSerializer.GetTypeInfo(JsonSerializerOptions, Type)
   at System.Text.Json.JsonSerializer.GetTypeInfo[T](JsonSerializerOptions)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](Utf8JsonReader&, JsonSerializerOptions )
   at Devsense.LanguageServer.JsonRpc.MessageStreamReader.ReadRequest()
   at Devsense.LanguageServer.JsonRpc.MessageStreamReader.<.ctor>b__5_0(Object _)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
[Info  - 11:03:32 AM] Connection to server got closed. Server will restart.
Unhandled exception. System.InvalidOperationException: JsonSerializerIsReflectionDisabled
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_JsonSerializerIsReflectionDisabled()
   at System.Text.Json.JsonSerializerOptions.ConfigureForJsonSerializer()
   at System.Text.Json.JsonSerializerOptions.MakeReadOnly(Boolean)
   at System.Text.Json.JsonSerializer.GetTypeInfo(JsonSerializerOptions, Type)
   at System.Text.Json.JsonSerializer.GetTypeInfo[T](JsonSerializerOptions)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](Utf8JsonReader&, JsonSerializerOptions )
   at Devsense.LanguageServer.JsonRpc.MessageStreamReader.ReadRequest()
   at Devsense.LanguageServer.JsonRpc.MessageStreamReader.<.ctor>b__5_0(Object _)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
[Info  - 11:03:33 AM] Connection to server got closed. Server will restart.
Unhandled exception. System.InvalidOperationException: JsonSerializerIsReflectionDisabled
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_JsonSerializerIsReflectionDisabled()
   at System.Text.Json.JsonSerializerOptions.ConfigureForJsonSerializer()
   at System.Text.Json.JsonSerializerOptions.MakeReadOnly(Boolean)
   at System.Text.Json.JsonSerializer.GetTypeInfo(JsonSerializerOptions, Type)
   at System.Text.Json.JsonSerializer.GetTypeInfo[T](JsonSerializerOptions)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](Utf8JsonReader&, JsonSerializerOptions )
   at Devsense.LanguageServer.JsonRpc.MessageStreamReader.ReadRequest()
   at Devsense.LanguageServer.JsonRpc.MessageStreamReader.<.ctor>b__5_0(Object _)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
[Info  - 11:03:34 AM] Connection to server got closed. Server will restart.
Unhandled exception. System.InvalidOperationException: JsonSerializerIsReflectionDisabled
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_JsonSerializerIsReflectionDisabled()
   at System.Text.Json.JsonSerializerOptions.ConfigureForJsonSerializer()
   at System.Text.Json.JsonSerializerOptions.MakeReadOnly(Boolean)
   at System.Text.Json.JsonSerializer.GetTypeInfo(JsonSerializerOptions, Type)
   at System.Text.Json.JsonSerializer.GetTypeInfo[T](JsonSerializerOptions)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](Utf8JsonReader&, JsonSerializerOptions )
   at Devsense.LanguageServer.JsonRpc.MessageStreamReader.ReadRequest()
   at Devsense.LanguageServer.JsonRpc.MessageStreamReader.<.ctor>b__5_0(Object _)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
[Info  - 11:03:34 AM] Connection to server got closed. Server will restart.
Unhandled exception. System.InvalidOperationException: JsonSerializerIsReflectionDisabled
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_JsonSerializerIsReflectionDisabled()
   at System.Text.Json.JsonSerializerOptions.ConfigureForJsonSerializer()
   at System.Text.Json.JsonSerializerOptions.MakeReadOnly(Boolean)
   at System.Text.Json.JsonSerializer.GetTypeInfo(JsonSerializerOptions, Type)
   at System.Text.Json.JsonSerializer.GetTypeInfo[T](JsonSerializerOptions)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](Utf8JsonReader&, JsonSerializerOptions )
   at Devsense.LanguageServer.JsonRpc.MessageStreamReader.ReadRequest()
   at Devsense.LanguageServer.JsonRpc.MessageStreamReader.<.ctor>b__5_0(Object _)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
[Error - 11:03:35 AM] Connection to server got closed. Server will not be restarted.
```
![image](https://github.com/DEVSENSE/phptools-docs/assets/42226341/58b23a99-57be-4449-9c24-e1ef25b574ed)

**Comment by jakubmisek** [comment]
Sorry for that. Releasing update asap.
